export const NODE_DIMENSIONS = [
    {
        key: "orgCat",
        title: "Organization Category",
        dataKey: "orgTypePrimary",
        arrayKey: "orgTypes",
        filterContainerId: "orgCategoryFilters",
        selectionContainerId: "selectionOrgCategoryFilters",
        filterStateKey: "allowedOrgCategories",
        selectionStateKey: "selectedOrgCategories",
        filterLogKey: "orgCats",
        selectionLogKey: "selectionOrgCats",
        filterStatus: { label: "Organization categories", singular: "category" },
        search: { key: "orgTypes", label: "Organization type", order: 30 },
        order: [
            "Tribal Sovereign",
            "Government",
            "Quasi Governmental",
            "Coordination Structure",
            "Academic",
            "Nonprofit Community",
            "Private Sector",
            "Media",
            "Other",
        ],
        colors: {
            "Academic": "#4E79A7",
            "Coordination Structure": "#F28E2B",
            "Government": "#E15759",
            "Media": "#76B7B2",
            "Nonprofit Community": "#59A14F",
            "Private Sector": "#EDC948",
            "Quasi Governmental": "#B07AA1",
            "Tribal Sovereign": "#9C755F",
            "Other": "#9E9E9E",
        },
        fallbackColor: "#9E9E9E",
    },
    {
        key: "nodeType",
        title: "Node Type",
        dataKey: "nodeTypePrimary",
        arrayKey: "nodeTypes",
        filterContainerId: "nodeTypeFilters",
        selectionContainerId: "selectionNodeTypeFilters",
        filterStateKey: "allowedNodeTypes",
        selectionStateKey: "selectedNodeTypes",
        filterLogKey: "nodeTypes",
        selectionLogKey: "selectionNodeTypes",
        filterStatus: { label: "Node types", singular: "type" },
        search: { key: "nodeTypes", label: "Node type", order: 20 },
        order: ["Hub", "Organization", "Program", "tribe", "Other"],
        colors: {
            "Hub": "#E15759",
            "Organization": "#4E79A7",
            "Program": "#F28E2B",
            "tribe": "#59A14F",
            "Other": "#9E9E9E",
        },
        fallbackColor: "#9E9E9E",
    },
    {
        key: "governance",
        title: "Governance Level",
        dataKey: "governanceLevelPrimary",
        arrayKey: "governanceLevels",
        filterContainerId: "governanceFilters",
        selectionContainerId: "selectionGovernanceFilters",
        filterStateKey: "allowedGovernanceLevels",
        selectionStateKey: "selectedGovernanceLevels",
        filterLogKey: "governanceLevels",
        selectionLogKey: "selectionGovernanceLevels",
        filterStatus: { label: "Governance levels", singular: "level" },
        search: { key: "governanceLevels", label: "Governance", order: 50 },
        order: [
            "Federal",
            "State",
            "Local",
            "Multi",
            "Non Governmental",
            "Private",
            "Sovereign",
            "Other",
        ],
        colors: {
            "Federal": "#4E79A7",
            "State": "#F28E2B",
            "Local": "#E15759",
            "Multi": "#76B7B2",
            "Non Governmental": "#EDC948",
            "Private": "#59A14F",
            "Sovereign": "#9C755F",
            "Other": "#9E9E9E",
        },
        fallbackColor: "#9E9E9E",
    },
    {
        key: "functionalDomain",
        title: "Functional Domain",
        dataKey: "functionalDomainPrimary",
        arrayKey: "functionalDomains",
        filterContainerId: "functionalDomainFilters",
        selectionContainerId: "selectionFunctionalDomainFilters",
        filterStateKey: "allowedFunctionalDomains",
        selectionStateKey: "selectedFunctionalDomains",
        filterLogKey: "functionalDomains",
        selectionLogKey: "selectionFunctionalDomains",
        filterStatus: { label: "Functional domains", singular: "domain" },
        search: { key: "functionalDomains", label: "Functional domain", order: 60 },
        order: [
            "Community Resilience",
            "Earthquake Science",
            "Emergency Management",
            "Infrastructure Systems",
            "Other",
        ],
        colors: {
            "Community Resilience": "#76B7B2",
            "Earthquake Science": "#E15759",
            "Emergency Management": "#F28E2B",
            "Infrastructure Systems": "#4E79A7",
            "Other": "#9E9E9E",
        },
        fallbackColor: "#9E9E9E",
    },
    {
        key: "role",
        title: "Role",
        dataKey: "rolePrimary",
        arrayKey: "roleTags",
        filterContainerId: "roleFilters",
        selectionContainerId: "selectionRoleFilters",
        filterStateKey: "allowedRoles",
        selectionStateKey: "selectedRoles",
        filterLogKey: "roles",
        selectionLogKey: "selectionRoles",
        filterStatus: { label: "Roles", singular: "role" },
        search: { key: "roleTags", label: "Role", order: 70 },
        order: [
            "Coordination",
            "Data Tools Provider",
            "Emergency Response",
            "Funding Provider",
            "Infrastructure Operator",
            "Knowledge Provider",
            "Messaging Alerts Provider",
            "Policy Maker Regulator",
            "Other",
        ],
        colors: {
            "Coordination": "#4E79A7",
            "Data Tools Provider": "#76B7B2",
            "Emergency Response": "#E15759",
            "Funding Provider": "#EDC948",
            "Infrastructure Operator": "#F28E2B",
            "Knowledge Provider": "#59A14F",
            "Messaging Alerts Provider": "#B07AA1",
            "Policy Maker Regulator": "#9C755F",
            "Other": "#9E9E9E",
        },
        fallbackColor: "#9E9E9E",
    },
    {
        key: "lifeline",
        title: "FEMA Lifeline",
        dataKey: "femaLifelinePrimary",
        arrayKey: "lifelineTags",
        filterContainerId: "lifelineFilters",
        selectionContainerId: "selectionLifelineFilters",
        filterStateKey: "allowedLifelines",
        selectionStateKey: "selectedLifelines",
        filterLogKey: "lifelines",
        selectionLogKey: "selectionLifelines",
        filterStatus: { label: "FEMA lifelines", singular: "lifeline" },
        search: { key: "lifelineTags", label: "FEMA lifeline", order: 80 },
        order: [
            "Communications",
            "Energy",
            "Food Hydration Shelter",
            "Health Medical",
            "Safety Security",
            "Transportation",
            "Water Systems",
            "Other",
        ],
        colors: {
            "Communications": "#F28E2B",
            "Energy": "#E15759",
            "Food Hydration Shelter": "#EDC948",
            "Health Medical": "#B07AA1",
            "Safety Security": "#4E79A7",
            "Transportation": "#59A14F",
            "Water Systems": "#76B7B2",
            "Other": "#9E9E9E",
        },
        fallbackColor: "#9E9E9E",
    },
    {
        key: "geo",
        title: "Geographic Area",
        dataKey: "geoPrimary",
        arrayKey: "geoTags",
        filterContainerId: "geoFilters",
        selectionContainerId: "selectionGeoFilters",
        filterStateKey: "allowedGeos",
        selectionStateKey: "selectedGeos",
        filterLogKey: "geos",
        selectionLogKey: "selectionGeos",
        filterStatus: {
            label: "Geographies",
            singular: "geography",
            plural: "geographies",
        },
        search: { key: "geoPrimary", label: "Geography", order: 40 },
        order: [
            "International",
            "Canada",
            "U.S. National",
            "PNW Regional",
            "British Columbia",
            "Washington",
            "Oregon",
            "California",
            "Other",
        ],
        colors: {
            "British Columbia": "#59A14F",
            "California": "#76B7B2",
            "Canada": "#EDC948",
            "International": "#FF9DA7",
            "Oregon": "#E15759",
            "PNW Regional": "#B07AA1",
            "U.S. Federal": "#9C755F",
            "U.S. National": "#4E79A7",
            "Washington": "#F28E2B",
            "Other": "#9E9E9E",
        },
        fallbackColor: "#9E9E9E",
    },
];

function controlSpec(dimension, type) {
    const isFilter = type === "filter";
    return {
        containerId: isFilter
            ? dimension.filterContainerId
            : dimension.selectionContainerId,
        title: dimension.title,
        visualKey: dimension.key,
        stateKey: isFilter
            ? dimension.filterStateKey
            : dimension.selectionStateKey,
        logKey: isFilter
            ? dimension.filterLogKey
            : dimension.selectionLogKey,
        arrayKey: dimension.arrayKey,
        primaryKey: dimension.dataKey,
        order: dimension.order,
        filterStatus: dimension.filterStatus,
    };
}

export const NODE_DIMENSION_BY_KEY = Object.fromEntries(
    NODE_DIMENSIONS.map((dimension) => [dimension.key, dimension])
);

export const NODE_FILTER_SPECS = NODE_DIMENSIONS.map((dimension) =>
    controlSpec(dimension, "filter")
);

export const NODE_SELECTION_SPECS = [
    ...NODE_DIMENSIONS.map((dimension) => controlSpec(dimension, "selection")),
    {
        containerId: "selectionOrganizationFilters",
        title: "All Organizations",
        stateKey: "selectedOrganizations",
        logKey: "selectionOrganizations",
        primaryKey: "orgName",
        previewLimit: 5,
        visibleOnly: true,
    },
];
