export const visualSpec = {
    nodes: {
        orgCat: {
            dataKey: "orgTypePrimary",
            title: "Organization Category",
            order: [
                "Tribal Sovereign",
                "Government",
                "Quasi Governmental",
                "Coordination Structure",
                "Academic",
                "Nonprofit Community",
                "Private Sector",
                "Media",
                "Unknown",
            ],
            colors: {
                "Academic": "#4E79A7",
                "Coordination Structure": "#F28E2B",
                "Government": "#E15759",
                "Media": "#76B7B2",
                "Nonprofit Community": "#59A14F",
                "Private Sector": "#EDC948",
                "Quasi Governmental": "#B07AA1",
                "Tribal Sovereign": "#9C755F",
                "Unknown": "#9E9E9E",
            },
            fallbackColor: "#9E9E9E",
        },
        nodeType: {
            dataKey: "nodeTypePrimary",
            title: "Node Type",
            order: ["Hub", "Organization", "Program", "Unknown"],
            colors: {
                "Hub": "#E15759",
                "Organization": "#4E79A7",
                "Program": "#F28E2B",
                "Unknown": "#9E9E9E",
            },
            fallbackColor: "#9E9E9E",
        },
        governance: {
            dataKey: "governanceLevelPrimary",
            title: "Governance Level",
            order: [
                "Federal",
                "State",
                "Local",
                "Multi",
                "Non Governmental",
                "Private",
                "Sovereign",
                "Unknown",
            ],
            colors: {
                "Federal": "#4E79A7",
                "State": "#F28E2B",
                "Local": "#E15759",
                "Multi": "#76B7B2",
                "Non Governmental": "#EDC948",
                "Private": "#59A14F",
                "Sovereign": "#9C755F",
                "Unknown": "#9E9E9E",
            },
            fallbackColor: "#9E9E9E",
        },
        functionalDomain: {
            dataKey: "functionalDomainPrimary",
            title: "Functional Domain",
            order: [
                "Community Resilience",
                "Earthquake Science",
                "Emergency Management",
                "Infrastructure Systems",
                "Unknown",
            ],
            colors: {
                "Community Resilience": "#76B7B2",
                "Earthquake Science": "#E15759",
                "Emergency Management": "#F28E2B",
                "Infrastructure Systems": "#4E79A7",
                "Unknown": "#9E9E9E",
            },
            fallbackColor: "#9E9E9E",
        },
        role: {
            dataKey: "rolePrimary",
            title: "Role",
            order: [
                "Coordination",
                "Data Tools Provider",
                "Emergency Response",
                "Funding Provider",
                "Infrastructure Operator",
                "Knowledge Provider",
                "Messaging Alerts Provider",
                "Policy Maker Regulator",
                "Unknown",
            ],
            colors: {
                "Coordination": "#4E79A7",
                "Data Tools Provider": "#76B7B2",
                "Emergency Response": "#E15759",
                "Funding Provider": "#EDC948",
                "Infrastructure Operator": "#F28E2B",
                "Knowledge Provider": "#59A14F",
                "Messaging Alerts Provider": "#B07AA1",
                "Policy Maker Regulator": "#9C755F",
                "Unknown": "#9E9E9E",
            },
            fallbackColor: "#9E9E9E",
        },
        lifeline: {
            dataKey: "femaLifelinePrimary",
            title: "FEMA Lifeline",
            order: [
                "Communications",
                "Energy",
                "Food Hydration Shelter",
                "Health Medical",
                "Safety Security",
                "Transportation",
                "Water Systems",
                "Unknown",
            ],
            colors: {
                "Communications": "#F28E2B",
                "Energy": "#E15759",
                "Food Hydration Shelter": "#EDC948",
                "Health Medical": "#B07AA1",
                "Safety Security": "#4E79A7",
                "Transportation": "#59A14F",
                "Water Systems": "#76B7B2",
                "Unknown": "#9E9E9E",
            },
            fallbackColor: "#9E9E9E",
        },
        geo: {
            dataKey: "geoPrimary",
            title: "Geographic Area",
            order: [
                "International",
                "Canada",
                "U.S. National",
                "PNW Regional",
                "British Columbia",
                "Washington",
                "Oregon",
                "California",
                "Unknown",
            ],
            colors: {
                "British Columbia": "#59A14F",
                "California": "#76B7B2",
                "Canada": "#EDC948",
                "International": "#FF9DA7",
                "Oregon": "#E15759",
                "PNW Regional": "#B07AA1",
                "U.S. Federal": "#9C755F",
                "U.S. National": "#4E79A7",
                "Washington": "#F28E2B",
                "Unknown": "#9E9E9E",
            },
            fallbackColor: "#9E9E9E",
        },
    },

    edges: {
        relType: {
            dataKey: "relType",
            title: "Relationship Type",
            order: [
                "funding",
                "emergency response coordination",
                "info/research",
                "tools/products",
                "data",
            ],
            colors: {
                "funding": "#E15759",
                "emergency response coordination": "#F28E2B",
                "info/research": "#4E79A7",
                "tools/products": "#59A14F",
                "data": "#B07AA1",
            },
            fallbackColor: "#9E9E9E",
        },
    },
};
